"""SQLModel table definitions for the tournament.

Entity overview
---------------
``Student``        — a participant, linked to a Telegram account and one team.
``Team``           — a company of (up to) three students competing in the market.
``Round``          — one Cournot round targeting a single econometric method.
``Decision``       — a team's quantity + written reasoning for a round.
``Result``         — the computed market outcome and rubric score for a decision.
``RubricTemplate`` — a per-method set of grading criteria authored by the professor.

The numeric outcomes on :class:`Result` are produced by the deterministic engine
in :mod:`core.market_engine`; nothing here computes economics itself.
"""

from datetime import UTC, datetime
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel, UniqueConstraint

from db.enums import Method, Role, RoundStatus

__all__ = [
    "Student",
    "Team",
    "Round",
    "Decision",
    "Result",
    "RubricTemplate",
]


def _utcnow() -> datetime:
    """Return a timezone-aware UTC timestamp (avoids deprecated ``utcnow``)."""
    return datetime.now(UTC)


class Student(SQLModel, table=True):
    """A student participant, identified by their Telegram account."""

    id: int | None = Field(default=None, primary_key=True)
    telegram_id: int = Field(unique=True, index=True)
    full_name: str
    team_id: int | None = Field(default=None, foreign_key="team.id", index=True)
    role: Role | None = None

    team: Optional["Team"] = Relationship(back_populates="students")


class Team(SQLModel, table=True):
    """A company controlled by a team of students."""

    id: int | None = Field(default=None, primary_key=True)
    name: str  # e.g. "Команда А"
    company_name: str  # e.g. "Роснефть", "Газпром"
    cumulative_profit: float = 0.0

    students: list[Student] = Relationship(back_populates="team")
    decisions: list["Decision"] = Relationship(back_populates="team")


class Round(SQLModel, table=True):
    """One Cournot round. Market parameters mirror :class:`core.MarketParameters`."""

    id: int | None = Field(default=None, primary_key=True)
    number: int = Field(index=True)
    method: Method
    difficulty: int  # 1..6
    status: RoundStatus = Field(default=RoundStatus.DRAFT, index=True)
    market_a: float
    market_b: float
    market_mc: float
    case_narrative: str = ""  # generated by Groq; empty until generated
    created_at: datetime = Field(default_factory=_utcnow)

    decisions: list["Decision"] = Relationship(back_populates="round")


class Decision(SQLModel, table=True):
    """A team's submission for a round: chosen quantity plus written reasoning.

    A team may submit only once per round, enforced by a composite unique
    constraint on ``(team_id, round_id)``.
    """

    __table_args__ = (UniqueConstraint("team_id", "round_id", name="uq_team_round"),)

    id: int | None = Field(default=None, primary_key=True)
    team_id: int = Field(foreign_key="team.id", index=True)
    round_id: int = Field(foreign_key="round.id", index=True)
    quantity: float
    reasoning: str  # the team's justification text (+ any AI interaction logs)
    submitted_at: datetime = Field(default_factory=_utcnow)

    team: Optional["Team"] = Relationship(back_populates="decisions")
    round: Optional["Round"] = Relationship(back_populates="decisions")
    result: Optional["Result"] = Relationship(back_populates="decision")


class Result(SQLModel, table=True):
    """Computed outcome for a decision: market result + rubric score.

    One-to-one with :class:`Decision` (enforced by a unique foreign key).
    ``rubric_breakdown_json`` stores a serialized ``GradingResult`` for audit.
    """

    id: int | None = Field(default=None, primary_key=True)
    decision_id: int = Field(foreign_key="decision.id", unique=True, index=True)
    price: float
    profit: float
    rubric_score: float = 0.0
    rubric_breakdown_json: str = ""  # serialized core grading result

    decision: Optional["Decision"] = Relationship(back_populates="result")


class RubricTemplate(SQLModel, table=True):
    """A per-method grading rubric authored by the professor via the dashboard.

    ``criteria_json`` holds a serialized ``list[RubricCriterion]`` (see
    :mod:`core.rubric_grader`). Stored as JSON text so the schema stays stable
    while criteria evolve.
    """

    id: int | None = Field(default=None, primary_key=True)
    method: Method = Field(index=True)
    name: str
    criteria_json: str
